name: vizoplayer
description: "A flutter project with clean architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # networking
  http: ^1.2.1
  dio: ^5.8.0+1

  # UI design
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.17
  go_router: ^14.8.1

  # Annotation
  riverpod_annotation: ^2.3.5

  connectivity_plus: ^6.1.3
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/app_icons/
    - assets/icons/basic_icons/
    - assets/icons/nav_icons/


  # fonts
  # 300 → Light
  # 400 → Regular (Default) *
  # 500 → Medium *
  # 600 → SemiBold *
  # 700 → Bold *
  # 800 → ExtraBold
  # 900 → Black
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: fonts/rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: fonts/rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
